- name: Set up Rabbit MQ hosts
  ansible.builtin.shell:
    cmd: |
      echo "{{ RABBIT_MASTER_IP }} rabbitmqmaster" | sudo tee -a /etc/hosts > /dev/null
      echo "{{ RABBIT_SLAVE_IP }} rabbitmqslave" | sudo tee -a /etc/hosts > /dev/null
  register: setup_output

- name: Display the content of the file
  ansible.builtin.debug:
    msg: "{{ setup_output.stdout }}"

- name: Start RabbitMQ service and enable on boot
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Fetch .erlang.cookie file from rabbitmqmaster to control node
  ansible.builtin.fetch:
    src: /var/lib/rabbitmq/.erlang.cookie
    dest: /tmp/erlang.cookie
    flat: yes
    fail_on_missing: yes
  delegate_to: "{{ RABBIT_MASTER_IP }}"
  register: fetch_result

- name: Debug fetch task result
  ansible.builtin.debug:
    var: fetch_result

- name: Copy .erlang.cookie file from control node to rabbitmqslave
  ansible.builtin.copy:
    src: /tmp/erlang.cookie
    dest: /var/lib/rabbitmq/.erlang.cookie
    #owner: root
    #group: root
  delegate_to: "{{ RABBIT_SLAVE_IP }}"
  when: fetch_result is succeeded

- name: Start RabbitMQ in master and all nodes
  ansible.builtin.service:
    name: rabbitmq-server
    state: started

- name: Stop RabbitMQ cluster
  ansible.builtin.shell: rabbitmqctl stop_app
  delegate_to: "{{ RABBIT_SLAVE_IP }}"

- name: Join RabbitMQ cluster
  ansible.builtin.shell: rabbitmqctl join_cluster rabbit@rabbitmqmaster
  delegate_to: "{{ RABBIT_SLAVE_IP }}"

- name: start RabbitMQ cluster
  ansible.builtin.shell: rabbitmqctl start_app
  delegate_to: "{{ RABBIT_SLAVE_IP }}"

- name: Check RabbitMQ cluster status
  ansible.builtin.shell: rabbitmqctl cluster_status
  register: cluster_status
  delegate_to: "{{ RABBIT_MASTER_IP }}"

- debug:
    var: cluster_status.stdout

- name: Set HA Policy in Master node
  ansible.builtin.shell: |
    if [[ "{{ ansible_hostname }}" == "{{ RABBIT_MASTER_IP }}" ]]; then
      sudo rabbitmqctl set_policy ha-all "" '{"ha-mode":"all", "ha-sync-mode":"automatic"}'
    fi

